<?php ?>
<header>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen and (min-device-width: 1200px)" href="/css/desktop.css" />
    <link rel="stylesheet" href="/css/css.css">
    <link rel="stylesheet" href="/css/print.css" type="text/css" media="print" />
    <div id="header">
    <img alt="Logo" id="header_logo" src="/images/header.png" style="width: 100%;height: 25%">
    </div>
    <nav id="nav">
        <a href="/"> Úvod</a>
        <a href="/clanky"> Články</a>
        <a href="/kontakt"> Kontakt</a>
        <?php
        if(!$user->isLogged())
        {
            echo '<a href="/prihlaseni"> Přihlášení</a>';
            echo '<a href="/registrace"> Registrace</a>';
        }
        else
        {
            if (!$user->isLoggedRegistrovany()){
                echo '<a href="/administrace"> Administrace</a>';
            }
            echo '<a href="/odhlaseni"> Odhlašení ze systému</a>';
        }
        ?>
    </nav>
</header>