<?php ?>
<header>

    <div id="header">
    <img alt="Logo" id="header_logo" src="../images/logo.jpg">
    </div>
    <nav id="nav">
        <a href="/"> Úvod</a>
        <a href="/clanky"> Články</a>
        <a href="/kontakt"> Kontakt</a>
        <?php
        if(!$user->isLogged())
        {
            echo '<a href="/prihlaseni"> Přihlášení</a>';
            echo '<a href="/registrace"> Registrace</a>';
        }
        else
        {
            if (!$user->isLoggedRegistrovany()){
                echo '<a href="/administrace"> Administrace</a>';
            }
            echo '<a href="/odhlaseni"> Odhlašení ze systému</a>';
        }
        ?>
    </nav>
</header>