<?php ?>
<header>

    <div id="header">
    <img alt="Logo" id="header_logo" src="../images/logo.jpg">
    </div>
    <nav id="nav">
        <a href="/"> Úvod</a>
        <a href="/clanky"> Články</a>
        <a href="/kontakt"> Kontakt</a>
        <a href="/prihlaseni"> Přihlášení</a>
        <a href="/registrace"> Registrace</a>
        <a href="/administrace"> Administrace</a>
    </nav>
</header>