<?php
include $_SERVER['DOCUMENT_ROOT'] . "/config/loggedOrRegistrovany.php";
?>

<div class="adminMenu">
    <nav>
    <h1>Administrace</h1>
    <h2>Články</h2>
    <a href="administrace/clanek/pridat" class="button">Přidat článek</a>
    <?php if ($_SESSION['userPrivileges'] === 'admin'){echo'<a href="administrace/clanek/seznam" class="button">Seznam článků</a>';}?>
    <h2>Tagy</h2>
    <a href="administrace/tagy/pridat" class="button">Přidat tagy</a>
<?php if ($_SESSION['userPrivileges'] === 'admin'){echo'<a href="administrace/tagy/seznam" class="button">Seznam tagů</a>
    <h2>Tagy článků</h2>
    <a href="administrace/tagy_clanku/pridat" class="button">Přidat tagy do článků</a>
    <a href="administrace/tagy_clanku/seznam" class="button">Seznam tagů v článcích</a>
    <h2>Uživatelé</h2>
    <a href="administrace/uzivatele/pridat" class="button">Přidat uživatele</a>
    <a href="administrace/uzivatele/seznam" class="button">Seznam uživatelů</a>';}?>
    </nav>
</div>