<?php ?>
<div>
    <h1>Články</h1>
    <div class="thumbnails">
    <?php
    $articles = $db->getAllArticleByCreated();
    foreach ($articles as $article) {
        echo'<div class="articleThumbnail" style="display: flex">';
        echo'<div class="flexDate"<p>' . $article['created'] . '</p></div>';
        echo'<div class="flexClanek"><p id="flexLink"><a href="/clanek?id=' . $article['idArticles'] . '">' . $article['title'] . '</a></p><p>' . $article['description']. '</p>';
        $tags = $db->getArticleTags($article['idArticles']); ?>
        <p><?php echo 'Tagy: <b>';
            foreach ($tags as $row) {
                //Get name of each tag paired with the article
                $tag = $db->getTag($row["idTags"]);
                $tagName = $tag["name"]??'';
                echo  $tagName . ' ';
            } echo '</b></p></div>';
        $rating = $db->getArticleRating($article['idArticles']);
        if ($rating[0] === 0)
            echo '<div class="flexRating"><p><b>Článek zatím nebyl hodnocen</b></p><p><i>Komentářů: </i><b>' . $db->getArticleCommentsCount($article['idArticles']). '</b></p></div>';
        else{echo '<div class="flexRating"><p><b>' . $rating[0] .'/10</b></p><p><i>Komentářů: </i><b>' . $db->getArticleCommentsCount($article['idArticles']). '</b></p></div>';
        }
        echo '</div>';
    }

    ?>
    </div>
</div>