<?php

$id = $_GET['id'];
/** @var DB $db */
/** @var USER $user */
$article = $db->getArticle($id);
$title = $article["title"]?? '';
$description = $article["description"]?? '';
$content = $article["content"]?? '';
$created = $article["created"]?? '';
$userID = $article["idUsers"]?? '';

$user = $db->getUserById($userID);
$userName = $user["name"]?? '';
$userNameLast = $user["lastName"]?? '';
//get ids of tags paired to this article
$tags = $db->getArticleTags($id);

if (isset($_GET['del'])) {
    $priv = $_SESSION['userPrivileges'] ??'';
    if ($priv === 'admin'){
    $idComment = $_GET['del'] ??'';
    $db->deleteComment($idComment);
    header("Location: /clanek?id=$id");
    }
}

?>
<div>
    <h1><?php echo $title?></h1>
    <hr>
    <div class="metadata">
        <p>Autor: <?php echo $userName . ' ' . $userNameLast?></p>
        <p><?php echo $created?></p>
    </div>
    <div class="tags">
        <p>Tagy: <?php
            foreach ($tags as $row) {
                //Get name of each tag paired with the article
                $tag = $db->getTag($row["idTags"]);
                $tagName = $tag["name"]??'';
                echo  $tagName . ' ';
            }?></p>
    </div>
    <div class="getRating">
        <p>Hodnocení článku: <b><?php $pole =$db->getArticleRating($id);
        if ($pole[0] === 0)
            echo 'NaN';
        else{
        echo $pole[0];}?>/10</b></p>
        <p class="ratingCount"><i>(Počet uživatelů, kteří ohodnotili článek: <?php echo $pole[1]?>)</i></p>
    </div>
    <hr>
    <div class="content">
        <p><?php echo $content?><p>
    </div>
    <hr>
    <?php
    if (isset($_SESSION['userName'])){
        if (!$db->getUserAlreadyRate($id,$_SESSION['userId']??'')){
            echo '<div class="setRating">';
            echo '<form method="post">';
            echo '<label for="rating">Ohodnoť článek:</label>';
            echo '<select name="ratingCombo">';
            echo '<option value="1">1</option>';
            echo '<option value="2">2</option>';
            echo '<option value="3">3</option>';
            echo '<option value="4">4</option>';
            echo '<option value="5">5</option>';
            echo '<option value="6">6</option>';
            echo '<option value="7">7</option>';
            echo '<option value="8">8</option>';
            echo '<option value="9">9</option>';
            echo '<option value="10">10</option>';
            echo '</select>';
            echo '<button name="submitRating" type="submit" class="rating_btn">Odeslat hodnocení</button>';
            echo '</form>';
            echo '</div>';
            echo '<hr>';
        }else{
            echo '<p><i>Tento článek jsi již hodnotil. Dal jsi mu: ' . $db->getUserArticleRate($id,$_SESSION['userId']) .'/10</i></p>';
            echo '<hr>';
        }
        echo '<div class ="commentAdd">';
        echo '<form method="post">';
            echo '<label for="commentcontent"><b>Přidat komentář:</b></label>';
            echo '<textarea rows="4" maxlength="255" placeholder="Text komentáře" name="commentcontent" id="commentcontent" cols="50" required></textarea>';
            echo '<button name="submitComment" type="submit" id="add_comment_btn">Odeslat komentář</button>';
        echo '</form>';
        echo '</div>';
        echo '<hr>';
    }
    ?>
    <div class="comments">
        <h2>Komentáře</h2>
        <?php
            $privileges = $_SESSION['userPrivileges'] ??'';
            $comments = $db->getAllArticleComments($id);
            $counter = 0;
            foreach ($comments as $row){
                $counter++;
                echo'<div class="comment">';
                    if ($privileges === 'admin')
                        echo'<p>#' . $counter . ' ' .'<a href="/clanek?id=' . $id . '&del=' . $row['idComments'] . '" ' . 'class="del_btn">Smazat komentář</a></p>';
                    else {echo'<p>#' . $counter . '</p>';}
                    echo'<p>' . $row['name'] . ' ' . $row['lastName'] . '(' . $row['privileges'] . ') ' . $row['created'] . '</p>';
                    echo'<p class="comment">'. $row['content'] .'</p>';
                echo'</div>';
            }
        ?>
        <hr>
    </div>
</div>
<?php
if (isset($_POST['submitRating'])){
    $value = $_POST['ratingCombo'] ?? '';
    $db->insertRating($value,$id,$_SESSION['userId']);
    header("Location: /clanek?id=$id");
} elseif (isset($_POST['submitComment'])){
    $content = $_POST['commentcontent'] ?? '';
    $db->insertComment($content,$id,$_SESSION['userId']);
    header("Location: /clanek?id=$id");
}
