<div>
    <h1>Úvod</h1>
    <h2>Nejnovější článek</h2>
    <?php
    $article = $db->getAllArticleByCreated()[0];
    $rating = $db->getArticleRating($article['idArticles']);
    ?>
    <div class="articleThumbnail" style="display: flex">
        <div><p><?php echo $article['created']; ?></p></div>
        <div><p><a href="/clanek?id=<?php echo $article['idArticles']; ?>"><?php echo $article['title']; ?></a></p>
            <p><?php echo $article['description']; ?></p>
            <?php $tags = $db->getArticleTags($article['idArticles']); ?>
            <p><?php echo 'Tagy: ';
                foreach ($tags as $row) {
                    //Get name of each tag paired with the article
                    $tag = $db->getTag($row["idTags"]);
                    $tagName = $tag["name"]??'';
                    echo  $tagName . ' ';
                }?></p></div>
        <div><p><?php if ($rating[0] === 0)
                echo 'NaN';
                else{
                echo $rating[0];}?>/10</p>
            <p><i>Komentářů: </i><?php echo $db->getArticleCommentsCount($article['idArticles'])?></p></div>
    </div>
</div>

