<div>
    <h1>Úvod</h1>
    <h2>Nejnovější článek</h2>
    <?php
    $article = $db->getAllArticleByCreated()[0];
    $rating = $db->getArticleRating($article['idArticles']);
    ?>
    <div class="thumbnails">
    <div class="articleThumbnail" style="display: flex">
        <div class="flexDate"><p><?php echo $article['created']; ?></p></div>
        <div class="flexClanek"><p id="flexLink"><a href="/clanek?id=<?php echo $article['idArticles']; ?>"><?php echo $article['title']; ?></a></p>
            <p><?php echo $article['description']; ?></p>
            <?php $tags = $db->getArticleTags($article['idArticles']); ?>
            <p><?php echo 'Tagy: <b>';
                foreach ($tags as $row) {
                    //Get name of each tag paired with the article
                    $tag = $db->getTag($row["idTags"]);
                    $tagName = $tag["name"]??'';
                    echo  $tagName . ' ';
                }?></b></p></div>
        <div class="flexRating"><p><b><?php if ($rating[0] === 0)
                echo 'Článek zatím nebyl hodnocen';
                else{
                    echo $rating[0] . '/10';}?></b></p>
            <p><i>Komentářů: </i><b><?php echo $db->getArticleCommentsCount($article['idArticles'])?></b></p></div>
    </div>
    </div>
</div>

