<?php ?>
<div>
    <form action="XXX.php">
        <div class="TODO">
            <h1>Přihlášení do systému</h1>
            <p>Prosím vyplňte své údaje.</p>
            <hr>

            <label for="email"><b>Email</b></label>
            <input type="email" placeholder="Zadej email" name="email" id="email" required>

            <label for="psw"><b>Heslo</b></label>
            <input type="password" placeholder="Zadej heslo" name="psw" id="psw" required>
            <hr>


            <button type="submit" class="login_btn">Přihlásit</button>
        </div>

        <div class="TODO">
            <p>Ještě nemáš svůj účet ? <a href="/registrace">Registrace</a></p>
        </div>
    </form>
</div>