<h1>Registrace nového uživatele</h1>
<div>
    <form method="post" action="">
        <div class="form">

            <p>Vyplňte registrační formulář.</p>
            <hr>

            <label for="email"><b>Email</b></label>
            <input type="email" placeholder="Zadej email" name="email" id="email" required>

            <label for="psw"><b>Heslo</b></label>
            <input type="password" placeholder="Zadej heslo" name="psw" id="psw" required>

            <label for="psw_repeat"><b>Heslo (pro kontrolu)</b></label>
            <input type="password" placeholder="Zadej znovu heslo" name="psw_repeat" id="psw_repeat" required>

            <label for="name"><b>Jméno</b></label>
            <input type="text" placeholder="Zadej jméno" name="name" id="name" required>

            <label for="last_name"><b>Příjmení</b></label>
            <input type="text" placeholder="Zadej příjmení" name="last_name" id="last_name" required>
            <hr>
            <button name="submit" type="submit" id="register_btn">Zaregistrovat</button>
        </div>

        <div class="form">
            <p>Už máš účet ? <a href="/prihlaseni">Přihlášení</a></p>
        </div>
    </form>
</div>
<?php
/**
 * @var DB $db
 */

// REGISTER USER
if (isset($_POST['submit'])) {
    $email = htmlspecialchars(!empty($_POST['email']) ? trim($_POST['email']) : null);
    $pass1 = htmlspecialchars(!empty($_POST['psw']) ? trim($_POST['psw']) : null);
    $pass2 = htmlspecialchars(!empty($_POST['psw_repeat']) ? trim($_POST['psw_repeat']) : null);
    $name = htmlspecialchars(!empty($_POST['name']) ? trim($_POST['name']) : null);
    $last_name = htmlspecialchars(!empty($_POST['last_name']) ? trim($_POST['last_name']) : null);
    //var_dump($db->userExist($email)); //test
    if ($pass1 != $pass2){
        echo("<p class='alert'>hesla se neshodují</p>");
    }else{
        if ($db->userExist($email)){
            echo("<p class='alert'>Uzivatel jiz existuje</p>");
        }else{
            $db->insertUser($email,$pass1,$name,$last_name);
            echo("<p class='info'><b>Uzivatel zaregistrován</b></p>");
        }

    }


}
?>