<?php
include $_SERVER['DOCUMENT_ROOT'] . "/config/onlyadmin.php";

if (isset($_GET['del'])) {
    $id = $_GET['del'];
    $db->deleteArticleComplet($id);
    header("Location: /administrace/clanek/seznam");
}

?>
<div>
<table style="table-layout: fixed; width:100%;">
    <thead>
    <tr>
        <th style="width: 7%">Id článku</th>
        <th>Název</th>
        <th>Popis</th>
        <th>Obsah</th>
        <th>Vytvořen</th>
        <th style="width: 7%">Id uživatele</th>
        <th colspan="2" style="width: 10%">Akce</th>
    </tr>
    </thead>

    <?php
    $articles = $db->getAllArticles();
    foreach ($articles as $row) { ?>
        <tr>
            <td><?php echo $row['idArticles']; ?></td>
            <td><?php echo $row['title']; ?></td>
            <td><?php echo $row['description']; ?></td>
            <td style="overflow: hidden; white-space: nowrap;text-overflow: ellipsis; "><?php echo $row['content']; ?></td>
            <td><?php echo $row['created']; ?></td>
            <td><?php echo $row['idUsers']; ?></td>
            <td>
                <a href="/administrace/clanek/upravit?edit=<?php echo $row['idArticles']; ?>" class="edit_btn" >
                    <img alt="upravit" style="width: 50%" src='/images/edit.png'/></a>
            </td>
            <td>
                <a href="/administrace/clanek/seznam?del=<?php echo $row['idArticles']; ?>" class="del_btn">
                    <img alt="smazat" style="width: 50%" src='/images/del.png'/></a>
            </td>
        </tr>
    <?php } ?>
</table>
    <hr>
    <div>
        <form action="" method="post" enctype="multipart/form-data">
        <label for="privileges"><b>Export JSON</b></label>
        <button name="exportJson" type="submit" id="export_json_btn">Download file</button>
            <hr>
        <label for="privileges"><b>Import JSON</b></label>
        <input type="file" name="fileToUpload" id="fileToUpload">
        <button name="importJson" type="submit">Importovat</button>
        </form>
    </div>
</div>
<?php
if(isset($_POST['exportJson'])){
    $json = json_encode($db->getAllArticles(),JSON_UNESCAPED_UNICODE);

    ob_start();
    echo $json;
    $htmlStr = ob_get_contents();
    ob_end_clean();
    $file_url = 'json/export.json';
    file_put_contents($file_url, $htmlStr);

    header('Content-Type: application/octet-stream');
    header("Content-Transfer-Encoding: Binary");
    header("Content-disposition: attachment; filename=\"" . basename($file_url) . "\"");
    ob_clean();
    flush();
    readfile($file_url);
    exit();
} elseif (isset($_POST['importJson'])){
    $target_dir = "json";
    $target_file = $target_dir . basename($_FILES["fileToUpload"]["name"]??'');
    $imageFileType = strtolower(pathinfo($target_file,PATHINFO_EXTENSION));
    echo $imageFileType;

    if(move_uploaded_file($_FILES["fileToUpload"]["tmp_name"]??'', $target_file)){
        $records = json_decode(file_get_contents($target_file),JSON_UNESCAPED_UNICODE);
        if($records != NULL){
            foreach ($records as $rec){
                $idArticles = $rec['idArticles'];
                $title = $rec['title'];
                $description = $rec['description'];
                $content = $rec['content'];
                $idUsers = $rec['idUsers'];
                $db->insertArticle($title,$description,$content,$idUsers);
                header("Location: /administrace/clanek/seznam");
            }
        } else {
            $error = "<p class='alert'>Neplatny typ souboru</p>";
        }
    } else {
        $error = "<p class='alert'>Nepodařilo se nahrát soubor na server</p>";
    }

}


?>


