<?php
include $_SERVER['DOCUMENT_ROOT'] . "/config/onlyadmin.php";

if (isset($_GET['edit'])) {
    $id = $_GET['edit'];
    $article = $db->getArticle($id);

}

?>
<div>
    <h1>Úprava článku</h1>
    <form method="post" action="">
        <div class="form">

            <hr>

            <label for="title"><b>Titulek</b></label>
            <input type="text" value="<?php echo $article["title"];?>" name="title" id="title" required>

            <label for="description"><b>Popis</b></label>
            <textarea rows="4" maxlength="255" name="description" id="description" required><?php echo $article["description"];?></textarea>

            <label for="content"><b>Obsah</b></label>
            <textarea rows="30" cols="60" name="content" id="content" required><?php echo $article["content"];?></textarea>

            <label for="idUsers"><b>Id uživatele</b></label>
            <input type="number" value="<?php echo $article["idUsers"];?>" name="idUsers" id="idUsers" required>

            <label for="checkbox"><b>Tagy</b></label>
            <?php
            $tags = $db->getAllTags();
            $articleTags = $db->getArticleTags($id);
            foreach ($tags as $row) {
                $isChecked=0;
                foreach ($articleTags as $articleTag)
                    if ($row["idTags"] === $articleTag["idTags"]){
                        echo  '<input type="checkbox" name="checkbox[]" value="'.$row["idTags"].'" checked/>'; //'.$id.'
                        echo  '<label for="checkbox">' . $row["name"] . '</label>';
                        $isChecked =1;
                    }
                if ($isChecked ===0){
                    echo  '<input type="checkbox" name="checkbox[]" value="'.$row["idTags"].'"/>'; //'.$id.'
                    echo  '<label for="checkbox">' . $row["name"] . '</label>';
                }
            }
            ?>

            <hr>
            <button name="submit" type="submit" id="edit_article_btn">Upravit článek</button>
        </div>
    </form>
</div>
<?php
if (isset($_POST['submit'])) {
    $title = $_POST['title'] ?? '';
    $description = $_POST['description'] ?? '';
    $content = $_POST['content'] ?? '';
    $userid = $_POST['idUsers'] ?? '';

    $db->updateArticle($title,$description,$content,$userid,$id);
    $articleTags = $db->getArticleTags($id);
    foreach ($articleTags as $articleTag){
        $db->deleteArticleTagsByTagID($articleTag["idTags"]);
    }
    $checkboxes = isset($_POST['checkbox']) ? $_POST['checkbox'] : array();
    foreach($checkboxes as $value) {
        $db->insertArticleTag($value,$id);
    }

    header("Location: /administrace/clanek/upravit?edit=$id");

}
