<?php
session_start();
include_once("../config/config.php");
echo("test2");
// REGISTER USER
if (isset($_POST['submit'])) {
    echo("postPred");
    // receive all input values from the form
    $username = !empty($_POST['email']) ? trim($_POST['email']) : null;
    $pass = !empty($_POST['psw']) ? trim($_POST['psw']) : null;
    echo($username);
    echo($pass);
    echo("postPo");

}
echo("test44");
